### ISSUE TITLE
Small suggestion about multi-monitor situations

### ISSUE THREAD

**Issue by Vovkiv** [togfoxy/SpaceFleetBattles#8]
On this line https://github.com/togfoxy/SpaceFleetBattles/blob/f10590765655e50ff3fadca208bbc66c5778925c/SpaceFleetBattles/main.lua#L111
I noticed that to set window size, you get monitor size from 1 monitor, even if game window on 2nd or 3nd monitor.
It's not that uncommon for desktop user to have 2 or more monitors, especially with different resolutions on each. What i want to suggest is what done in this example, near end: https://love2d.org/wiki/love.window.getDesktopDimensions
So your code will look like:
```lua
local _, _, flags = love.window.getMode()

-- The window's flags contain the index of the monitor it's currently in.
local width, height = love.window.getDesktopDimensions(flags.display)
res.setMode(width, height, {resizable = true})
```
After that, game window should get proper size of screen, based on which monitor game window is placed.
Also check other situations where you might interact with screen data, so it will use current monitor instead of fixed 1st.

**Comment by togfoxy** [comment]
This is great - thanks! You are right. I was half lazy and half making assumptions about monitors. Making that small change gives great benefits.

Feel free to comment any time!

**Comment by Vovkiv** [comment]
Yep, i'm smart cookie.
I also want to point out to you this useful guideline: https://gameaccessibilityguidelines.com/
It's nice collection of tips and advices about making your game more accessibly, like adding gamepad support or adding subtitles for players with bad hearing abilities. This advices might be not that useful for small prototyped games, but it's still useful information, that you want to use more, depending on scale of you games
